In [1]:
import numpy as np

# создание массива

In [2]:
arr = np.array([1,2,3])

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr.shape

(3,)

объединение массивов

In [5]:
arr2 = np.append(arr, [4, 7, 6])

In [6]:
arr, arr2

(array([1, 2, 3]), array([1, 2, 3, 4, 7, 6]))

In [7]:
arr3 = np.append(arr2, [[1, 2],
                        [3, 4]])

In [8]:
arr3

array([1, 2, 3, 4, 7, 6, 1, 2, 3, 4])

In [9]:
arr3.shape

(10,)

In [10]:
list2 = [[1, 5, 1, 3],
         [5, 6, 1, 4],
         [1, 4, 6, 9]] #создания списка с списками одинакового размера (двухмерный список)

создание двухмерного массива (матрицы)

In [11]:
arr2_2 = np.array(list2)

In [12]:
arr2_2.shape

(3, 4)

In [13]:
type(arr2_2)

numpy.ndarray

# создание массивов заданной размерностью и значениями

In [14]:
arr_0 = np.zeros((5, 1))
arr_0

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [15]:
arr_0 = np.zeros((5, 4))
arr_0

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr_1 = np.ones((4, 2, 2)) # четырёхмерный массив из единиц размером 4 на 2 на 2 
arr_1

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [17]:
np.eye(10) # единичная матрица

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [18]:
np.empty((2, 2)) # массив заполненный мусором (как бы пустой)

array([[4.9e-324, 9.9e-324],
       [1.5e-323, 2.0e-323]])

In [19]:
np.empty((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

# создание последовательностей чисел

In [20]:
a = np.arange(0, 11, 3)
a

array([0, 3, 6, 9])

In [21]:
b = np.arange(100, 0, -1)
print(b)

[100  99  98  97  96  95  94  93  92  91  90  89  88  87  86  85  84  83
  82  81  80  79  78  77  76  75  74  73  72  71  70  69  68  67  66  65
  64  63  62  61  60  59  58  57  56  55  54  53  52  51  50  49  48  47
  46  45  44  43  42  41  40  39  38  37  36  35  34  33  32  31  30  29
  28  27  26  25  24  23  22  21  20  19  18  17  16  15  14  13  12  11
  10   9   8   7   6   5   4   3   2   1]


In [22]:
np.set_printoptions(threshold=10, precision=8) # изменим параметры вывода
print(b) # теперь выводится меньше, но информации передаёт вывод ровно столько, сколько передавал!
type(b)

[100  99  98 ...   3   2   1]


numpy.ndarray

# базовые операции

In [23]:
arr1 = np.ones((4, 4))
arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], shape=(4, 4))

In [24]:
arr2 = np.ones((4, 4))

In [25]:
c = arr1 + arr2
c

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]], shape=(4, 4))

In [26]:
c - arr1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], shape=(4, 4))

In [27]:
c *= c
c

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]], shape=(4, 4))

In [28]:
c / c

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], shape=(4, 4))

In [29]:
np.inf * -1

-inf

In [30]:
np.inf - np.inf

nan

In [31]:
np.array([1]) / 0 # делить на 0 оказывается можно-то!

/tmp/ipykernel_38795/327077814.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([1]) / 0 # делить на 0 оказывается можно-то!


array([inf])

In [32]:
c *= 2
c

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]], shape=(4, 4))

In [33]:
c = c ** c
c

array([[16777216., 16777216., 16777216., 16777216.],
       [16777216., 16777216., 16777216., 16777216.],
       [16777216., 16777216., 16777216., 16777216.],
       [16777216., 16777216., 16777216., 16777216.]], shape=(4, 4))

In [34]:
c = c ** 1/1000
c

array([[16777.216, 16777.216, 16777.216, 16777.216],
       [16777.216, 16777.216, 16777.216, 16777.216],
       [16777.216, 16777.216, 16777.216, 16777.216],
       [16777.216, 16777.216, 16777.216, 16777.216]], shape=(4, 4))

In [35]:
2 ** (np.ones((2, 2)) * 3)

array([[8., 8.],
       [8., 8.]])

In [36]:
a = np.ones((4, 3)) # транспонируем матрицу
b = np.transpose(a)
a, b

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], shape=(4, 3)),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], shape=(3, 4)))

In [37]:
b = np.transpose(b) * 4
a *= 3
a * b

array([[12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.],
       [12., 12., 12.]], shape=(4, 3))

# тригонометрия и округления

In [38]:
a

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]], shape=(4, 3))

In [39]:
np.cos(a)

array([[-0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925],
       [-0.9899925, -0.9899925, -0.9899925]], shape=(4, 3))

In [40]:
b = np.arctan(a)
b

array([[1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577],
       [1.24904577, 1.24904577, 1.24904577]], shape=(4, 3))

In [41]:
np.round(b, 2)

array([[1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25],
       [1.25, 1.25, 1.25]], shape=(4, 3))

In [42]:
np.ceil(b)

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]], shape=(4, 3))

In [43]:
np.fix(b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], shape=(4, 3))

# Агрегирующие функции

In [44]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [45]:
np.sum(a)

np.float64(9.0)

In [46]:
np.min(a)

np.float64(1.0)

In [47]:
np.max(a)

np.float64(1.0)

In [48]:
a = np.array([[1, 2, 8],
              [4, 5, 6]])

In [49]:
a.min(axis=1) # минимум по строкам

array([1, 4])

In [50]:
a.min(axis=0) # минимум по столбцам

array([1, 2, 6])

# Индексы, срезы и итерации

In [51]:
a = np.arange(10, 0, -1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [52]:
a[-1]

np.int64(1)

In [53]:
a[4:7]

array([6, 5, 4])

In [54]:
a[[0,-1]]

array([10,  1])

In [55]:
a[::-1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [56]:
b = np.array([[ 0,  1,  2,  3],
...           [10, 11, 12, 13],
...           [20, 21, 22, 23],
...           [30, 31, 32, 33],
...           [40, 41, 42, 43]]) # двумерный массив
b

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]], shape=(5, 4))

In [57]:
b[3,1]

np.int64(31)

In [58]:
b[[-1, 0]] # вывод строк

array([[40, 41, 42, 43],
       [ 0,  1,  2,  3]])

In [59]:
b[:,[0, 2]] # вывод столбцов

array([[ 0,  2],
       [10, 12],
       [20, 22],
       [30, 32],
       [40, 42]])

In [60]:
b[1:3,1:3]

array([[11, 12],
       [21, 22]])

In [61]:
b[:2]

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [62]:
b[100] # невозможно обратиться к несуществующей строке

IndexError: index 100 is out of bounds for axis 0 with size 5

# Итерирование массивов

In [ ]:
a = np.ones((4, 4))
a[2, 2] = 5
a[-1,-1] = 3

In [ ]:
for row in a:
    print(row)

In [ ]:
for n in a.flat: print(n)

In [ ]:
a

In [ ]:
a.ravel() # возвращает копию плоского массива

In [ ]:
a.shape = (8, 2) # изменяет форму массива (сам исходный массив меняется)

In [ ]:
a

In [ ]:
b = a.transpose() # копия транспонированного массива
b

In [ ]:
a

In [ ]:
a.reshape((4,4)) # изменение формы и возврат копии массива

In [ ]:
a

# объединение и разбиение массивов

In [ ]:
a = np.arange(0, 4)
b = np.arange(3, -1, -1)

In [ ]:
a

In [ ]:
b

In [ ]:
a = a.reshape((2,2))
b = b.reshape((2,2))
print(a, b)

In [ ]:
np.hstack((a, b))

In [ ]:
np.vstack((b, a))

In [ ]:
np.stack((b, a))

In [ ]:
np.vsplit(np.hstack((a, b)), 2)

In [ ]:
arr = np.hsplit(np.hstack((a, b)), 4)

In [ ]:
arr

In [ ]:
arr[0][0]

# Копии и представления

In [ ]:
a = np.arange(10)
a

In [ ]:
b = a

In [ ]:
b

In [ ]:
b is a # b и a ссылаются на один объект

In [ ]:
b.shape = (5, 2)

In [ ]:
a # изменение объекта меняет значения b и a одновременно

In [ ]:
c = a.view()
c

In [ ]:
c is a

In [ ]:
a.shape = (2, 5)
c

In [ ]:
c[0][0] = 100
c[1,0] = 1000

In [ ]:
a

In [ ]:
c # view даёт создавать разные представления, но значения остаются общие (ячейки памяти общие)

In [ ]:
d = a.copy()

In [ ]:
d is a

In [ ]:
d[0,0] = 999
a

In [ ]:
d # теперь всё хранится в разных ячейках памяти

# случайные числа

In [ ]:
import numpy as np
import numpy.random as rand

In [ ]:
np.random.sample(10) * 100

In [ ]:
np.random.sample((1, 2, 2, 2))

In [ ]:
np.random.randint(0, 3, 10)

In [ ]:
arr = np.random.uniform(0, 101, (2, 2))
arr

In [ ]:
np.random.shuffle(arr)
arr

# инициализация генератора случайных чисел

In [ ]:
np.random.seed(2**32 - 1) # размер таблицы случайных чисел найден!
np.random.random(10)

In [ ]:
np.random.seed(0)
np.random.random(10)

In [ ]:
np.random.seed(1)
np.random.random(10)